
SELECT CAST(DATEADD(mm, DATEDIFF(mm, 0, GETDATE()), 0) AS DATE) curr

SELECT cast(DATEADD(month, DATEDIFF(month, 0, GETDATE())-1, 0) AS DATE) m1
SELECT CAST(DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE()),0)) AS DATE)m1e

SELECT cast(DATEADD(month, DATEDIFF(month, 0, GETDATE())-2, 0) AS DATE) m2
SELECT CAST(DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE()) -1,0)) AS DATE)m2e

SELECT cast(DATEADD(month, DATEDIFF(month, 0, GETDATE())-3, 0) AS DATE) m2
SELECT CAST(DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE()) -2,0)) AS DATE)m2e